### PR TITLE
Generate JSON output for hanabi.live

### PR DESCRIPTION
**Pull request by felixbauckholt**
Now, you can generate JSON output for a game that you can then upload to [hanabi.live](https://hanabi.live/).

You can specify an output "file pattern" with the `--json-output` option; `%s` will be replaced by the game's seed. You can also pass the `--losses-only` option to only write out lost games.

I'm not convinced this is the user interface and code you should merge right now, I'm just putting this out there to prevent others from independently developing their own output method, and anybody has advice or comments. (Is `serde_json` the right library to use? Are "file patterns" a good idea and if so, is there a more standard thing to do than finding and replacing `%s`?)

One important detail of the [hanabi.live](https://hanabi.live/) format is that each card is specified by its initial position in the deck. Currently I'm doing a bunch of work to "annotate" each card with its initial position, but hide those annotations from the strategies. If we like this kind of annotations, we could instead expose them to the strategies and refactor the strategy code around them! (For instance, we could represent the public information as a single hash map from annotations to `CardPossibilityTable`s.)

### CODE REVIEW

**Comment by WuTheFWasThat** [comment]
the 2nd commit looks fine if you want to merge that first, haven't looked at the first yet.  

I don't keep up with rust stuff (haven't used it since this project and you can see how old the commits are!), but I vaguely remember seeing serde_json, i'm sure it's fine!  

it sounds like a super reasonable thing for the framework to generally allow annotations on cards, seems like it would simplify things a fair bit!

**Comment by WuTheFWasThat** [comment]
have you tried viewing a game log on hanabi.live yet?  i'd be curious what some of the losses look like!

**Comment by felixbauckholt** [comment]
I just rebased and generated some games with the current version!

I probably won't have too much time to analyze them right now since I just started my job, sorry!

[games.zip](https://github.com/WuTheFWasThat/hanabi.rs/files/2996669/games.zip)

**Comment by WuTheFWasThat** [comment]
awesome, good luck with your job!

**Pull request merged**
